version: "3.8"

services:
  database:
    container_name: vitnode_postgres_dev
    image: postgres:16.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD-root}
      POSTGRES_DB: vitnode
    command: ["postgres", "-c", "log_statement=all"] # log all sql queries
    volumes:
      - ./docker/dev/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vitnode_dev

  pgadmin:
    container_name: vitnode_pgadmin_dev
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - vitnode_dev

networks:
  vitnode_dev:
