on:
  pull_request_target:
    types: [opened, edited]
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"feat": "ğŸ’¡ Feature", "fix": "ğŸ Bug", "breaking": "ğŸš¨ Breaking Changes", "docs": "ğŸ“– Documentation", "style": "ğŸ’… Style", "refactor": "ğŸš€ Performerce", "test": "ğŸ§ª Test"}'
